logging:
  level:
    org:
      springframework:
        security: DEBUG
        boot:
          autoconfigure: ERROR
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://application-service-db/application-db
    username: postgres
    password: dev@1234
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: put-your-client-id-here
            client-secret: put-your-secret-id-here
            redirectUri: http://localhost:3000/
            scope:
              - email
              - profile
app:
  auth:
    tokenSecret: demonstration
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/
      - http://localhost:3000
liquibase:
  change-log: classpath:/db.changelog/db.changelog-master.yaml
server:
  port: 8080
